package GUI;

public enum OptionData {

    PLASMASCORING,
    MAGENDEFENSEGRID,
    X89BACTERIALWEAPON,
    ANTIMASSDEFLECTOR,
    STRIKEWINGAMBUSH,
    WARFUNDING,
    MEMORIA1,
    MEMORIA2,
    TEKKLARLEGION,
    BARONYAGENT,
    SOLAGENT,
    BUNKER,
    DISABLE,
    EXPERIMENTALBATTLESTATION,
    FIGHTERPROTOTYPE,
    FIRETEAM,
    MORALEBOOST,
    BLITZ,
    SOLARFLAIR,
    ARGENTFLIGHTCOMMANDER,
    JOLNARCOMMANDER,
    L1Z1XCOMMANDER,
    WINNUCOMMANDER,
    PROPHECYOFIXTH,
    CONVENTIONSOFWAR,
    DEFENDINGINNEBULA,
    TITANSHERO
}
