package GUI;

public enum UnitCountData {

    FLAGSHIPCOUNT,
    WARSUNCOUNT,
    DREADNOUGHTCOUNT,
    CARRIERCOUNT,
    CRUISERCOUNT,
    DESTROYERCOUNT,
    FIGHTERCOUNT,
    MECHCOUNT,
    INFANTRYCOUNT,
    PDSCOUNT,
}
