package Units;

public enum UnitNames {
    FLAGSHIP,
    WARSUN,
    DREADNOUGHT,
    CARRIER,
    CRUISER,
    DESTROYER,
    FIGHTER,
    MECH,
    INFANTRY,
    PDS,
    FLAGSHIPUPGRADE,
    DREADNOUGHTUPGRADE,
    CARRIERUPGRADE,
    CRUISERUPGRADE,
    DESTROYERUPGRADE,
    FIGHTERUPGRADE,
    INFANTRYUPGRADE,
    PDSUPGRADE,
    OTHER
}
