package GUIData;

public enum UpgradeData {

    ISFLAGSHIPUPGRADED,
    ISDREADNOUGHTUPGRADED,
    ISCARRIERUPGRADED,
    ISCRUISERUPGRADED,
    ISDESTROYERUPGRADED,
    ISFIGHTERUPGRADED,
    ISINFANTRYUPGRADED,
    ISPDSUPGRADED,
}
